cache:
  - C:\Users\appveyor\.m2 -> **\pom.xml

install:
  - set MAVEN_VERSION=3.2.5
  - choco install maven -version %MAVEN_VERSION%
  - set PATH=%PATH%;C:\bin\apache-maven-%MAVEN_VERSION%\bin
  - set JAVA_HOME=C:\Program Files (x86)\Java\jdk1.8.0

build_script:
  - mvn verify

